[package]
name = "gh-housekeeper-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
globset.workspace = true
serde.workspace = true
thiserror.workspace = true
