[package]
name = "gh-housekeeper-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono.workspace = true
gh-housekeeper-core = { path = "../gh-housekeeper-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
